title: Helelism
email: your-email@example.com
description: >-
  A photography portfolio.
baseurl: "/helelism"
url: "https://mizuki-5055.github.io"
github_username: Mizuki-5055

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Collections
collections:
  gallery:
    output: false
