backend:
  name: github
  repo: Mizuki-5055/Mizuki-5055.github.io
  branch: main
  base_url: https://sveltia-cms-auth.hibitaeru.workers.dev

media_folder: images/uploads
public_folder: /images/uploads
